import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "First NextJS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-screen">
        {/* NAVBAR */}
        <Navbar />

        {/* LIKE THAT OUTLET */}
        <div>{children}</div>

        {/* FOOTER */}
        <footer className="p-2 bg-neutral-900 text-white py-24">
          This is a Footer
        </footer>
      </body>
    </html>
  );
}
